import test from 'node:test';import assert from 'node:assert/strict';import worker,{BackchannelRoom} from '../src/worker.mjs';
class Store{constructor(){this.data=new Map();}async get(k){return structuredClone(this.data.get(k));}async put(k,v){if(typeof k==='string')this.data.set(k,structuredClone(v));else for(const [a,b]of Object.entries(k))this.data.set(a,structuredClone(b));}async list({prefix}){return new Map([...this.data].filter(([k])=>k.startsWith(prefix)));}async setAlarm(t){this.alarm=t;}async delete(k){this.data.delete(k);}async deleteAll(){this.data.clear();}}
function setup(){const objects=new Map();const env={GITHUB_TEACHER_IDS:'43101723,999',ROOMS:{idFromName:x=>x,get:id=>{if(!objects.has(id)){const storage=new Store();objects.set(id,new BackchannelRoom({storage},env));}return {fetch:(input,init)=>objects.get(id).fetch(input instanceof Request?input:new Request(input,init))};}}};const call=(path,method='GET',body,headers={})=>worker.fetch(new Request('https://test/api'+path,{method,headers:{'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined}),env);return {call,objects,env};}
const clipId='ami-is1008b-b-383000-450300-v1';const run={clipId,complete:true,exposed:false,marks:[1,3]};
async function login(s,id=43101723){const auth=s.env.ROOMS.get('teacher-account');const issued=await auth.fetch('https://internal/auth/issue',{method:'POST',body:JSON.stringify({id,login:'teacher-test'})});assert.equal(issued.status,200);const {handoff}=await issued.json();const response=await s.call('/teacher/exchange','POST',{handoff});return (await response.json()).token;}
async function room(s){const teacherKey=await login(s);const r=await s.call('/rooms','POST',{clipId},{Authorization:'Bearer '+teacherKey});assert.equal(r.status,200);return {...await r.json(),teacherKey};}
test('GitHub teacher session required; students cannot read results before release',async()=>{const s=setup(),r=await room(s);assert.equal((await s.call('/rooms/'+r.code+'/results')).status,403);assert.equal((await s.call('/rooms/'+r.code+'/manage','POST',{action:'release'})).status,403);assert.equal((await s.call('/rooms/'+r.code+'/results','GET',null,{Authorization:'Bearer '+r.teacherKey})).status,200);});
test('60 simultaneous students retain all records; retried submission is idempotent',async()=>{const s=setup(),r=await room(s);const keys=Array.from({length:60},()=>crypto.randomUUID());const joined=await Promise.all(keys.map(key=>s.call('/rooms/'+r.code+'/join','POST',{key})));assert.ok(joined.every(x=>x.status===200));const submitted=await Promise.all(keys.map(key=>s.call('/rooms/'+r.code+'/submit','POST',{run},{'X-Participant-Key':key})));assert.ok(submitted.every(x=>x.status===200));assert.equal((await s.call('/rooms/'+r.code+'/submit','POST',{run},{'X-Participant-Key':keys[0]})).status,200);const d=await(await s.call('/rooms/'+r.code+'/results','GET',null,{Authorization:'Bearer '+r.teacherKey})).json();assert.equal(d.runs.length,60);assert.equal(d.submitted,60);assert.equal(new Set(d.runs.map(x=>x.participant)).size,60);});
test('malformed or wrong-clip records fail, no anonymous overwrite',async()=>{const s=setup(),r=await room(s),key=crypto.randomUUID();await s.call('/rooms/'+r.code+'/join','POST',{key});for(const bad of [{...run,marks:[NaN]},{...run,clipId:'other'},{...run,marks:[-1]},{...run,marks:[3,1]}])assert.equal((await s.call('/rooms/'+r.code+'/submit','POST',{run:bad},{'X-Participant-Key':key})).status,400);assert.equal((await s.call('/rooms/'+r.code+'/submit','POST',{run})).status,401);});
test('release closes collection and publishes only anonymous records; reopen hides results',async()=>{const s=setup(),r=await room(s),key=crypto.randomUUID(),h={Authorization:'Bearer '+r.teacherKey};await s.call('/rooms/'+r.code+'/join','POST',{key});await s.call('/rooms/'+r.code+'/submit','POST',{run:{...run,marks:[],reflection:'PRIVATE'}},{'X-Participant-Key':key});await s.call('/rooms/'+r.code+'/manage','POST',{action:'release'},h);const d=await(await s.call('/rooms/'+r.code+'/results')).json();assert.equal(d.runs.length,1);assert.ok(!JSON.stringify(d).includes('PRIVATE'));assert.ok(!JSON.stringify(d).includes(r.teacherKey));assert.equal((await s.call('/rooms/'+r.code+'/join','POST',{key:crypto.randomUUID()})).status,409);await s.call('/rooms/'+r.code+'/manage','POST',{action:'open'},h);assert.equal((await s.call('/rooms/'+r.code+'/results')).status,403);});
test('expiry removes activity and registration is bounded',async()=>{const s=setup(),r=await room(s);const obj=s.objects.get(r.code);let m=await obj.ctx.storage.get('meta');assert.ok(m.expiresAt>Date.now()+29*86400000);m.joined=60;await obj.ctx.storage.put('meta',m);assert.equal((await s.call('/rooms/'+r.code+'/join','POST',{key:crypto.randomUUID()})).status,409);await obj.alarm();assert.equal((await s.call('/rooms/'+r.code)).status,404);});

test('anonymous creation and forged teacher headers fail',async()=>{const s=setup();assert.equal((await s.call('/rooms','POST',{clipId})).status,401);const r=await room(s);assert.equal((await s.call('/rooms/'+r.code+'/results','GET',null,{'X-Verified-Teacher':'43101723','X-Teacher-Key':'old-secret'})).status,403);});
test('other approved teachers cannot manage or list another teacher room',async()=>{const s=setup(),r=await room(s),token=await login(s,999),h={Authorization:'Bearer '+token};assert.equal((await s.call('/rooms/'+r.code+'/manage','POST',{action:'release'},h)).status,403);const data=await(await s.call('/teacher/rooms','GET',null,h)).json();assert.equal(data.rooms.length,0);});
test('logout revokes the session; handoff is single-use; unapproved IDs fail',async()=>{const s=setup(),r=await room(s),h={Authorization:'Bearer '+r.teacherKey};await s.call('/teacher/logout','POST',null,h);assert.equal((await s.call('/rooms','POST',{clipId},h)).status,401);const auth=s.env.ROOMS.get('teacher-account');assert.equal((await auth.fetch('https://internal/auth/issue',{method:'POST',body:JSON.stringify({id:123,login:'visitor'})})).status,403);const {handoff}=await(await auth.fetch('https://internal/auth/issue',{method:'POST',body:JSON.stringify({id:43101723,login:'teacher'})})).json();assert.equal((await s.call('/teacher/exchange','POST',{handoff})).status,200);assert.equal((await s.call('/teacher/exchange','POST',{handoff})).status,401);});
test('OAuth uses state and PKCE; callback needs browser cookie; no GitHub repository scope',async()=>{const s=setup();Object.assign(s.env,{GITHUB_CLIENT_ID:'test-client',GITHUB_CLIENT_SECRET:'test-secret'});const start=await s.call('/teacher/start');assert.equal(start.status,302);const target=new URL(start.headers.get('location'));assert.equal(target.hostname,'github.com');assert.equal(target.searchParams.get('code_challenge_method'),'S256');assert.equal(target.searchParams.get('code_challenge').length,43);assert.equal(target.searchParams.get('scope'),null);const state=target.searchParams.get('state');const bad=await s.call('/teacher/callback?state='+state+'&code=example');assert.ok(bad.headers.get('location').endsWith('teacher-error=signin'));const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url,opts)=>{calls++;if(String(url).includes('access_token')){assert.ok(JSON.parse(opts.body).code_verifier);return Response.json({access_token:'fake-github-token'});}return Response.json({id:43101723,login:'kayaulai'});};try{const done=await s.call('/teacher/callback?state='+state+'&code=example','GET',null,{Cookie:'__Host-7a-oauth='+state});const handoff=new URL(done.headers.get('location')).hash.split('=')[1];const exchange=await s.call('/teacher/exchange','POST',{handoff});assert.equal(exchange.status,200);assert.equal((await exchange.json()).username,'kayaulai');await s.call('/teacher/callback?state='+state+'&code=example','GET',null,{Cookie:'__Host-7a-oauth='+state});assert.equal(calls,2);}finally{globalThis.fetch=original;}});
