import test from 'node:test';import assert from 'node:assert/strict';import worker,{BackchannelRoom} from '../src/worker.mjs';
class Store{constructor(){this.data=new Map();}async get(k){return structuredClone(this.data.get(k));}async put(k,v){if(typeof k==='string')this.data.set(k,structuredClone(v));else for(const [a,b]of Object.entries(k))this.data.set(a,structuredClone(b));}async list({prefix}){return new Map([...this.data].filter(([k])=>k.startsWith(prefix)));}async setAlarm(t){this.alarm=t;}async delete(k){this.data.delete(k);}async deleteAll(){this.data.clear();}}
function setup(){const objects=new Map();const env={GITHUB_TEACHER_IDS:'43101723,999',ROOMS:{idFromName:x=>x,get:id=>{if(!objects.has(id)){const storage=new Store();objects.set(id,new BackchannelRoom({storage},env));}return {fetch:(input,init)=>objects.get(id).fetch(input instanceof Request?input:new Request(input,init))};}}};const call=(path,method='GET',body,headers={})=>worker.fetch(new Request('https://test/api'+path,{method,headers:{'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined}),env);return {call,objects,env};}
const clipId='ami-is1008b-b-383000-450300-v1';const run={clipId,complete:true,exposed:false,marks:[1,3]};
async function login(s,id=43101723){const auth=s.env.ROOMS.get('teacher-account');const issued=await auth.fetch('https://internal/auth/issue',{method:'POST',body:JSON.stringify({id,login:'teacher-test'})});assert.equal(issued.status,200);const {handoff}=await issued.json();const response=await s.call('/teacher/exchange','POST',{handoff});return (await response.json()).token;}
async function room(s){const teacherKey=await login(s);const r=await s.call('/rooms','POST',{clipId},{Authorization:'Bearer '+teacherKey});assert.equal(r.status,200);return {...await r.json(),teacherKey};}
test('GitHub teacher session required; students cannot read results before release',async()=>{const s=setup(),r=await room(s);assert.equal((await s.call('/rooms/'+r.code+'/results')).status,403);assert.equal((await s.call('/rooms/'+r.code+'/manage','POST',{action:'release'})).status,403);assert.equal((await s.call('/rooms/'+r.code+'/results','GET',null,{Authorization:'Bearer '+r.teacherKey})).status,200);});
test('60 simultaneous students retain all records; retried submission is idempotent',async()=>{const s=setup(),r=await room(s);const keys=Array.from({length:60},()=>crypto.randomUUID());const joined=await Promise.all(keys.map(key=>s.call('/rooms/'+r.code+'/join','POST',{key})));assert.ok(joined.every(x=>x.status===200));const submitted=await Promise.all(keys.map(key=>s.call('/rooms/'+r.code+'/submit','POST',{run},{'X-Participant-Key':key})));assert.ok(submitted.every(x=>x.status===200));assert.equal((await s.call('/rooms/'+r.code+'/submit','POST',{run},{'X-Participant-Key':keys[0]})).status,200);const d=await(await s.call('/rooms/'+r.code+'/results','GET',null,{Authorization:'Bearer '+r.teacherKey})).json();assert.equal(d.runs.length,60);assert.equal(d.submitted,60);assert.equal(new Set(d.runs.map(x=>x.participant)).size,60);});
test('malformed or wrong-clip records fail, no anonymous overwrite',async()=>{const s=setup(),r=await room(s),key=crypto.randomUUID();await s.call('/rooms/'+r.code+'/join','POST',{key});for(const bad of [{...run,marks:[NaN]},{...run,clipId:'other'},{...run,marks:[-1]},{...run,marks:[3,1]}])assert.equal((await s.call('/rooms/'+r.code+'/submit','POST',{run:bad},{'X-Participant-Key':key})).status,400);assert.equal((await s.call('/rooms/'+r.code+'/submit','POST',{run})).status,401);});
test('release closes collection and publishes only anonymous records; reopen hides results',async()=>{const s=setup(),r=await room(s),key=crypto.randomUUID(),h={Authorization:'Bearer '+r.teacherKey};await s.call('/rooms/'+r.code+'/join','POST',{key});await s.call('/rooms/'+r.code+'/submit','POST',{run:{...run,marks:[],reflection:'PRIVATE'}},{'X-Participant-Key':key});await s.call('/rooms/'+r.code+'/manage','POST',{action:'release'},h);const d=await(await s.call('/rooms/'+r.code+'/results')).json();assert.equal(d.runs.length,1);assert.ok(!JSON.stringify(d).includes('PRIVATE'));assert.ok(!JSON.stringify(d).includes(r.teacherKey));assert.equal((await s.call('/rooms/'+r.code+'/join','POST',{key:crypto.randomUUID()})).status,409);await s.call('/rooms/'+r.code+'/manage','POST',{action:'open'},h);assert.equal((await s.call('/rooms/'+r.code+'/results')).status,403);});
test('expiry removes activity and registration is bounded',async()=>{const s=setup(),r=await room(s);const obj=s.objects.get(r.code);let m=await obj.ctx.storage.get('meta');assert.ok(m.expiresAt>Date.now()+29*86400000);m.joined=60;await obj.ctx.storage.put('meta',m);assert.equal((await s.call('/rooms/'+r.code+'/join','POST',{key:crypto.randomUUID()})).status,409);await obj.alarm();assert.equal((await s.call('/rooms/'+r.code)).status,404);});

test('anonymous creation and forged teacher headers fail',async()=>{const s=setup();assert.equal((await s.call('/rooms','POST',{clipId})).status,401);const r=await room(s);assert.equal((await s.call('/rooms/'+r.code+'/results','GET',null,{'X-Verified-Teacher':'43101723','X-Teacher-Key':'old-secret'})).status,403);});
test('other approved teachers cannot manage or list another teacher room',async()=>{const s=setup(),r=await room(s),token=await login(s,999),h={Authorization:'Bearer '+token};assert.equal((await s.call('/rooms/'+r.code+'/manage','POST',{action:'release'},h)).status,403);const data=await(await s.call('/teacher/rooms','GET',null,h)).json();assert.equal(data.rooms.length,0);});
test('logout revokes the session; handoff is single-use; unapproved IDs fail',async()=>{const s=setup(),r=await room(s),h={Authorization:'Bearer '+r.teacherKey};await s.call('/teacher/logout','POST',null,h);assert.equal((await s.call('/rooms','POST',{clipId},h)).status,401);const auth=s.env.ROOMS.get('teacher-account');assert.equal((await auth.fetch('https://internal/auth/issue',{method:'POST',body:JSON.stringify({id:123,login:'visitor'})})).status,403);const {handoff}=await(await auth.fetch('https://internal/auth/issue',{method:'POST',body:JSON.stringify({id:43101723,login:'teacher'})})).json();assert.equal((await s.call('/teacher/exchange','POST',{handoff})).status,200);assert.equal((await s.call('/teacher/exchange','POST',{handoff})).status,401);});
test('OAuth uses state and PKCE; callback needs browser cookie; no GitHub repository scope',async()=>{const s=setup();Object.assign(s.env,{GITHUB_CLIENT_ID:'test-client',GITHUB_CLIENT_SECRET:'test-secret'});const start=await s.call('/teacher/start');assert.equal(start.status,302);const target=new URL(start.headers.get('location'));assert.equal(target.hostname,'github.com');assert.equal(target.searchParams.get('code_challenge_method'),'S256');assert.equal(target.searchParams.get('code_challenge').length,43);assert.equal(target.searchParams.get('scope'),null);const state=target.searchParams.get('state');const bad=await s.call('/teacher/callback?state='+state+'&code=example');assert.ok(bad.headers.get('location').endsWith('teacher-error=signin'));const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url,opts)=>{calls++;if(String(url).includes('access_token')){assert.ok(JSON.parse(opts.body).code_verifier);return Response.json({access_token:'fake-github-token'});}return Response.json({id:43101723,login:'kayaulai'});};try{const done=await s.call('/teacher/callback?state='+state+'&code=example','GET',null,{Cookie:'__Host-7a-oauth='+state});const handoff=new URL(done.headers.get('location')).hash.split('=')[1];const exchange=await s.call('/teacher/exchange','POST',{handoff});assert.equal(exchange.status,200);assert.equal((await exchange.json()).username,'kayaulai');await s.call('/teacher/callback?state='+state+'&code=example','GET',null,{Cookie:'__Host-7a-oauth='+state});assert.equal(calls,2);}finally{globalThis.fetch=original;}});

test('repeat attempts remain separate, retries deduplicate, comparison keeps the first',async()=>{
 const s=setup(),r=await room(s),key=crypto.randomUUID(),h={'X-Participant-Key':key},t={Authorization:'Bearer '+r.teacherKey};const base='/rooms/'+r.code;
 await s.call(base+'/join','POST',{key});const first={...run,id:crypto.randomUUID()},second={...run,id:crypto.randomUUID(),marks:[5]};
 for(const item of [first,second,second])assert.equal((await s.call(base+'/submit','POST',{run:item},h)).status,200);
 const results=await(await s.call(base+'/results','GET',null,t)).json();assert.equal(results.submitted,1);assert.equal(results.totalSubmissions,2);assert.deepEqual(results.runs[0].marks,[1,3]);
 const audit=await(await s.call(base+'/audit','GET',null,t)).json();assert.equal(audit.attempts.length,2);assert.deepEqual(audit.attempts.map(a=>a.inComparison),[true,false]);assert.ok(audit.attempts.every(a=>a.submittedAt));
 const join=await(await s.call(base+'/join','POST',{key})).json();assert.deepEqual(new Set(join.completedAttemptIds),new Set([first.id,second.id]));
 await s.call(base+'/manage','POST',{action:'release'},t);assert.equal((await s.call(base+'/audit')).status,403);assert.equal((await s.call(base+'/submit','POST',{run:second},h)).status,200);assert.equal((await s.call(base+'/submit','POST',{run:{...second,marks:[6]}},h)).status,409);
 const shared=await(await s.call(base+'/results')).json();assert.ok(!JSON.stringify(shared.runs).includes('submittedAt'));
});
test('task events deduplicate, retain incomplete attempts and strip unsolicited personal fields',async()=>{
 const s=setup(),r=await room(s),key=crypto.randomUUID(),h={'X-Participant-Key':key},t={Authorization:'Bearer '+r.teacherKey};const base='/rooms/'+r.code;await s.call(base+'/join','POST',{key});
 const id=crypto.randomUUID(),events=['start','mark','page_reload','pause','undo','mark','discard'].map((type,i)=>({id:crypto.randomUUID(),type,at:new Date().toISOString(),position:i,name:'PRIVATE-NAME',ip:'PRIVATE-IP',reflection:'PRIVATE-NOTES'}));
 for(let i=0;i<2;i++)assert.equal((await s.call(base+'/events','POST',{attemptId:id,events},h)).status,200);
 const audit=await(await s.call(base+'/audit','GET',null,t)).json();assert.equal(audit.attempts.length,1);assert.equal(audit.attempts[0].events.length,7);assert.equal(audit.attempts[0].status,'discarded');assert.deepEqual(audit.attempts[0].marks,[5]);assert.ok(!JSON.stringify(audit).includes('PRIVATE-'));
 assert.equal((await s.call(base+'/submit','POST',{run:{...run,id}},h)).status,409);
 assert.equal((await s.call(base+'/events','POST',{attemptId:null,events:[{...events[0],type:'keystroke'}]},h)).status,400);
});

test('server generates an eight-character activity code; one browser key retains P number and receipts',async()=>{
 const s=setup(),r=await room(s),key=crypto.randomUUID(),base='/rooms/'+r.code;assert.match(r.code,/^[A-Z2-9]{8}$/);
 const first=await(await s.call(base+'/join','POST',{key})).json();assert.equal(first.participant,1);
 const attempt={...run,id:crypto.randomUUID()};const receipt=await(await s.call(base+'/submit','POST',{run:attempt},{'X-Participant-Key':key})).json();
 const again=await(await s.call(base+'/join','POST',{key})).json();assert.equal(again.participant,1);assert.equal(again.joined,1);assert.equal(again.receipts[0].submittedAt,receipt.submittedAt);assert.equal(again.receipts[0].attempt,1);
 const other=await(await s.call(base+'/join','POST',{key:crypto.randomUUID()})).json();assert.equal(other.participant,2);assert.deepEqual(other.receipts,[]);
});
test('removing a teacher from allowlist immediately invalidates an existing session',async()=>{const s=setup(),r=await room(s);s.env.GITHUB_TEACHER_IDS='999';assert.equal((await s.call('/rooms/'+r.code+'/audit','GET',null,{Authorization:'Bearer '+r.teacherKey})).status,401);});
test('event caps do not prevent completed attempt submission; retries do not consume more capacity',async()=>{
 const s=setup(),r=await room(s),key=crypto.randomUUID(),base='/rooms/'+r.code,h={'X-Participant-Key':key};await s.call(base+'/join','POST',{key});
 const id=crypto.randomUUID(),event={id:crypto.randomUUID(),type:'start',at:new Date().toISOString(),position:0};assert.equal((await s.call(base+'/events','POST',{attemptId:id,events:[event]},h)).status,200);
 const storage=s.objects.get(r.code).ctx.storage,m=await storage.get('meta');m.eventCount=20000;await storage.put('meta',m);
 assert.equal((await s.call(base+'/events','POST',{attemptId:id,events:[event]},h)).status,200);
 assert.equal((await s.call(base+'/events','POST',{attemptId:id,events:[{...event,id:crypto.randomUUID()}]},h)).status,429);
 assert.equal((await s.call(base+'/submit','POST',{run:{...run,id}},h)).status,200);
});

test('independent computers refresh only their own participant IDs and receipts after concurrent submissions',async()=>{
 const s=setup(),r=await room(s),base='/rooms/'+r.code,keys=Array.from({length:60},()=>crypto.randomUUID());
 const joined=await Promise.all(keys.map(async key=>(await(await s.call(base+'/join','POST',{key})).json())));assert.equal(new Set(joined.map(x=>x.participant)).size,60);
 const submissions=await Promise.all(keys.map(async(key,i)=>{const rr={...run,id:crypto.randomUUID(),marks:[i+0.5]};const receipt=await(await s.call(base+'/submit','POST',{run:rr},{'X-Participant-Key':key})).json();return {id:rr.id,receipt};}));
 const refreshed=await Promise.all(keys.map(async key=>(await(await s.call(base+'/join','POST',{key})).json())));
 refreshed.forEach((d,i)=>{assert.equal(d.participant,joined[i].participant);assert.equal(d.receipts.length,1);assert.equal(d.receipts[0].id,submissions[i].id);assert.equal(d.receipts[0].submittedAt,submissions[i].receipt.submittedAt);});
 const comparison=await(await s.call(base+'/results','GET',null,{Authorization:'Bearer '+r.teacherKey})).json();assert.equal(comparison.runs.length,60);assert.equal(comparison.joined,60);assert.equal(comparison.submitted,60);
});

test('fixed course page provisions one collection without teacher setup and keeps student receipts isolated',async()=>{
 const s=setup();const current=await Promise.all(Array.from({length:12},async()=>await(await s.call('/current')).json()));assert.equal(new Set(current.map(x=>x.code)).size,1);const code=current[0].code;assert.ok(current[0].shared);
 const keys=[crypto.randomUUID(),crypto.randomUUID()];for(const key of keys){const joined=await s.call('/rooms/'+code+'/join','POST',{key});assert.equal(joined.status,200);await s.call('/rooms/'+code+'/submit','POST',{run:{...run,id:crypto.randomUUID()}},{'X-Participant-Key':key});}
 const a=await(await s.call('/rooms/'+code+'/join','POST',{key:keys[0]})).json();const b=await(await s.call('/rooms/'+code+'/join','POST',{key:keys[1]})).json();assert.notEqual(a.participant,b.participant);assert.equal(a.receipts.length,1);assert.notEqual(a.receipts[0].id,b.receipts[0].id);
 assert.equal((await s.call('/rooms/'+code+'/audit')).status,403);assert.equal((await s.call('/rooms/'+code+'/results')).status,403);
 for(const id of [43101723,999]){const token=await login(s,id),h={Authorization:'Bearer '+token};assert.equal((await s.call('/rooms/'+code+'/audit','GET',null,h)).status,200);const list=await(await s.call('/teacher/rooms','GET',null,h)).json();assert.ok(list.rooms.some(x=>x.code===code));}
});
test('optional next class preserves previous collection and requires teacher login',async()=>{
 const s=setup(),first=await(await s.call('/current')).json();assert.equal((await s.call('/teacher/next','POST',{})).status,401);const teacher=await login(s);const next=await(await s.call('/teacher/next','POST',{},{Authorization:'Bearer '+teacher})).json();assert.notEqual(first.code,next.code);assert.equal((await(await s.call('/current')).json()).code,next.code);assert.equal((await s.call('/rooms/'+first.code)).status,200);
});

test('two recordings have separate automatic collections and results',async()=>{const s=setup(),other='ami-ib4010-a-172300-232900-v1';const a=await(await s.call('/current')).json(),b=await(await s.call('/current?clipId='+other)).json();assert.notEqual(a.code,b.code);assert.equal(b.clipId,other);assert.equal((await(await s.call('/current')).json()).code,a.code);const key=crypto.randomUUID();await s.call('/rooms/'+b.code+'/join','POST',{key});assert.equal((await s.call('/rooms/'+b.code+'/submit','POST',{run},{'X-Participant-Key':key})).status,400);assert.equal((await s.call('/rooms/'+b.code+'/submit','POST',{run:{...run,clipId:other}},{'X-Participant-Key':key})).status,200);assert.equal((await(await s.call('/rooms/'+a.code)).json()).submitted,0);assert.equal((await(await s.call('/rooms/'+b.code)).json()).submitted,1);assert.equal((await s.call('/current?clipId=bad')).status,400);});

test('long recordings accept late markers and keep separate collections from legacy recordings',async()=>{
 const s=setup();const old=await(await s.call('/current?clipId='+clipId)).json();const codes=[old.code];
 for(const [id,duration] of [['ami-es2003b-a-599500-765650-v1',166.15],['ami-is1005c-c-461490-609600-v1',148.11]]){
  const response=await s.call('/current?clipId='+id);assert.equal(response.status,200);const room=await response.json();codes.push(room.code);
  const key=crypto.randomUUID(),headers={'X-Participant-Key':key},base='/rooms/'+room.code;await s.call(base+'/join','POST',{key});
  const longRun={...run,id:crypto.randomUUID(),clipId:id,marks:[90,duration]};
  assert.equal((await s.call(base+'/submit','POST',{run:{...longRun,marks:[duration+.1]}},headers)).status,400);
  assert.equal((await s.call(base+'/submit','POST',{run:longRun},headers)).status,200);
  assert.equal((await s.call(base+'/submit','POST',{run:{...run,id:crypto.randomUUID()}},headers)).status,400);
  assert.equal((await(await s.call(base)).json()).duration,duration);
 }
 assert.equal(new Set(codes).size,3);assert.equal((await(await s.call('/rooms/'+old.code)).json()).submitted,0);
});
