import test from 'node:test';import assert from 'node:assert/strict';import worker,{BackchannelRoom} from '../src/worker.mjs';
class Store{constructor(){this.data=new Map();}async get(k){return structuredClone(this.data.get(k));}async put(k,v){if(typeof k==='string')this.data.set(k,structuredClone(v));else for(const [a,b]of Object.entries(k))this.data.set(a,structuredClone(b));}async list({prefix}){return new Map([...this.data].filter(([k])=>k.startsWith(prefix)));}async setAlarm(t){this.alarm=t;}async deleteAll(){this.data.clear();}}
function setup(){const objects=new Map();const env={ROOMS:{idFromName:x=>x,get:id=>{if(!objects.has(id)){const storage=new Store();objects.set(id,new BackchannelRoom({storage}));}return {fetch:(input,init)=>objects.get(id).fetch(input instanceof Request?input:new Request(input,init))};}}};const call=(path,method='GET',body,headers={})=>worker.fetch(new Request('https://test/api'+path,{method,headers:{'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined}),env);return {call,objects};}
const clipId='ami-is1008b-b-383000-450300-v1';const run={clipId,complete:true,exposed:false,marks:[1,3]};
async function room(s){const r=await s.call('/rooms','POST',{clipId});assert.equal(r.status,200);return r.json();}
test('teacher key required; students cannot read results before release',async()=>{const s=setup(),r=await room(s);assert.equal((await s.call('/rooms/'+r.code+'/results')).status,403);assert.equal((await s.call('/rooms/'+r.code+'/manage','POST',{action:'release'})).status,403);assert.equal((await s.call('/rooms/'+r.code+'/results','GET',null,{'X-Teacher-Key':r.teacherKey})).status,200);});
test('60 simultaneous students retain all records; retried submission is idempotent',async()=>{const s=setup(),r=await room(s);const keys=Array.from({length:60},()=>crypto.randomUUID());const joined=await Promise.all(keys.map(key=>s.call('/rooms/'+r.code+'/join','POST',{key})));assert.ok(joined.every(x=>x.status===200));const submitted=await Promise.all(keys.map(key=>s.call('/rooms/'+r.code+'/submit','POST',{run},{'X-Participant-Key':key})));assert.ok(submitted.every(x=>x.status===200));assert.equal((await s.call('/rooms/'+r.code+'/submit','POST',{run},{'X-Participant-Key':keys[0]})).status,200);const d=await(await s.call('/rooms/'+r.code+'/results','GET',null,{'X-Teacher-Key':r.teacherKey})).json();assert.equal(d.runs.length,60);assert.equal(d.submitted,60);assert.equal(new Set(d.runs.map(x=>x.participant)).size,60);});
test('malformed or wrong-clip records fail, no anonymous overwrite',async()=>{const s=setup(),r=await room(s),key=crypto.randomUUID();await s.call('/rooms/'+r.code+'/join','POST',{key});for(const bad of [{...run,marks:[NaN]},{...run,clipId:'other'},{...run,marks:[-1]},{...run,marks:[3,1]}])assert.equal((await s.call('/rooms/'+r.code+'/submit','POST',{run:bad},{'X-Participant-Key':key})).status,400);assert.equal((await s.call('/rooms/'+r.code+'/submit','POST',{run})).status,401);});
test('release closes collection and publishes only anonymous records; reopen hides results',async()=>{const s=setup(),r=await room(s),key=crypto.randomUUID(),h={'X-Teacher-Key':r.teacherKey};await s.call('/rooms/'+r.code+'/join','POST',{key});await s.call('/rooms/'+r.code+'/submit','POST',{run:{...run,marks:[],reflection:'PRIVATE'}},{'X-Participant-Key':key});await s.call('/rooms/'+r.code+'/manage','POST',{action:'release'},h);const d=await(await s.call('/rooms/'+r.code+'/results')).json();assert.equal(d.runs.length,1);assert.ok(!JSON.stringify(d).includes('PRIVATE'));assert.ok(!JSON.stringify(d).includes(r.teacherKey));assert.equal((await s.call('/rooms/'+r.code+'/join','POST',{key:crypto.randomUUID()})).status,409);await s.call('/rooms/'+r.code+'/manage','POST',{action:'open'},h);assert.equal((await s.call('/rooms/'+r.code+'/results')).status,403);});
test('expiry removes activity and registration is bounded',async()=>{const s=setup(),r=await room(s);const obj=s.objects.get(r.code);let m=await obj.ctx.storage.get('meta');assert.ok(m.expiresAt>Date.now()+29*86400000);m.joined=60;await obj.ctx.storage.put('meta',m);assert.equal((await s.call('/rooms/'+r.code+'/join','POST',{key:crypto.randomUUID()})).status,409);await obj.alarm();assert.equal((await s.call('/rooms/'+r.code)).status,404);});
