const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const core=require('../../../docs/week_7/7a/core.js');
function harness(){
 const elements=new Map(),saved=new Map(),events=[],downloads=[];class El{constructor(){this.value='';this.textContent='';this.open=false;this.marks=[];this.listeners={};this.children=[];this.dataset={};this.style={};this.currentTime=0;this.paused=true;}append(...e){this.children.push(...e);}replaceChildren(...e){this.children=e;}setAttribute(){}focus(){}addEventListener(n,f){this.listeners[n]=f;}pause(){this.paused=true;}async play(){this.paused=false;}load(){}click(){this.onclick?.();}}
 const document={getElementById:id=>{if(!elements.has(id))elements.set(id,new El());return elements.get(id);},querySelectorAll:()=>[],createElement:()=>new El(),createElementNS:()=>new El(),createTextNode:t=>t};
 const window={BC_CLIPS:[{id:'test-clip',duration:20,peaks:[0,1],transcript:[],title:'Test',meeting:'M',speaker:'A',sourceStart:0,sourceEnd:20,src:'audio.wav'}],BC_CORE:core,BC_CLASSROOM:{mode:'student',room:'TESTROOM',identityNamespace:'TESTROOM:key1',participant:1},dispatchEvent:e=>events.push(e),addEventListener:()=>{}};
 const context={window,document,location:{hash:'',search:''},localStorage:{getItem:k=>saved.get(k),setItem:(k,v)=>saved.set(k,v)},URLSearchParams,crypto:require('node:crypto').webcrypto,CustomEvent:class{constructor(type,opts){this.type=type;this.detail=opts?.detail;}},confirm:()=>true,setTimeout,Blob,URL:{createObjectURL:blob=>{downloads.push(blob);return "blob:test";},revokeObjectURL:()=>{}}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../../docs/week_7/7a/applet.js'),'utf8'),context);
 const el=id=>document.getElementById(id);el('audio').listeners.canplaythrough();return {el,window,events,saved,downloads};
}
test('practice markers are not logged and later attempt is flagged for prior listening',async()=>{const h=harness();await h.el('practice').onclick();h.el('audio').currentTime=2;h.el('mark').onclick();assert.ok(!h.events.some(e=>e.detail?.type==='mark'));h.el('audio').currentTime=15;h.el('audio').listeners.timeupdate();await h.el('start').onclick();h.el('audio').listeners.ended();assert.equal(h.window.BC_APP.snapshot().runs[0].exposed,true);});
test('opening then closing transcript remains prior exposure for the next attempt',async()=>{const h=harness();h.el('transcript-details').open=true;h.el('transcript-details').ontoggle();h.el('transcript-details').open=false;h.el('transcript-details').ontoggle();await h.el('start').onclick();h.el('audio').listeners.ended();assert.equal(h.window.BC_APP.snapshot().runs[0].exposed,true);});
test('secondary read-only tab disables recording and cannot overwrite saved work',async()=>{const h=harness();h.window.BC_CLASSROOM.readOnly=true;h.window.BC_APP.controls();assert.equal(h.el('start').disabled,true);await h.el('start').onclick();assert.equal(h.window.BC_APP.snapshot().active,false);h.el('reflection').value='other tab';h.el('reflection').oninput();assert.equal(h.saved.size,0);});

test('personal CSV keeps one participant number across repeated attempts',async()=>{const h=harness();await h.el('start').onclick();h.el('audio').listeners.ended();await h.el('start').onclick();h.el('audio').listeners.ended();h.el('csv').onclick();const lines=(await h.downloads[0].text()).trim().split('\r\n');assert.equal(lines.length,3);assert.equal(lines[1].split(',')[0],'1');assert.equal(lines[2].split(',')[0],'1');assert.equal(lines[1].split(',')[1],'1');assert.equal(lines[2].split(',')[1],'2');});

test('completed student round immediately shows own waveform and markers before teacher release',async()=>{const h=harness();await h.el('start').onclick();h.el('audio').currentTime=3;h.el('mark').onclick();h.el('audio').listeners.ended();assert.equal(h.el('comparison').hidden,false);assert.equal(h.el('comparison-title').textContent,'Your listening choices');assert.ok(h.el('wave').children.length);assert.equal(h.window.BC_APP.snapshot().runs[0].marks[0],3);assert.equal(h.el('class-view').disabled,true);});

test('teacher view never reloads or writes cached classroom results',()=>{const h=harness();h.window.BC_CLASSROOM.mode='teacher';h.window.BC_APP.select('test-clip');h.el('reflection').value='Teacher-only note';h.el('reflection').oninput();assert.equal(h.saved.size,0);assert.equal(h.window.BC_APP.snapshot().runs.length,0);h.window.BC_APP.clearView();assert.equal(h.el('comparison').hidden,true);});
