const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const core=require('../../../docs/week_7/7a/core.js');
function harness(){
 const elements=new Map(),saved=new Map(),events=[];class El{constructor(){this.value='';this.textContent='';this.open=false;this.marks=[];this.listeners={};this.children=[];this.dataset={};this.style={};this.currentTime=0;this.paused=true;}append(...e){this.children.push(...e);}replaceChildren(...e){this.children=e;}setAttribute(){}focus(){}addEventListener(n,f){this.listeners[n]=f;}pause(){this.paused=true;}async play(){this.paused=false;}load(){}click(){this.onclick?.();}}
 const document={getElementById:id=>{if(!elements.has(id))elements.set(id,new El());return elements.get(id);},querySelectorAll:()=>[],createElement:()=>new El(),createElementNS:()=>new El(),createTextNode:t=>t};
 const window={BC_CLIPS:[{id:'test-clip',duration:20,peaks:[0,1],transcript:[],title:'Test',meeting:'M',speaker:'A',sourceStart:0,sourceEnd:20,src:'audio.wav'}],BC_CORE:core,BC_CLASSROOM:{mode:'student',room:'TESTROOM',identityNamespace:'TESTROOM:key1',participant:1},dispatchEvent:e=>events.push(e),addEventListener:()=>{}};
 const context={window,document,location:{hash:'',search:''},localStorage:{getItem:k=>saved.get(k),setItem:(k,v)=>saved.set(k,v)},URLSearchParams,crypto:require('node:crypto').webcrypto,CustomEvent:class{constructor(type,opts){this.type=type;this.detail=opts?.detail;}},confirm:()=>true,setTimeout,Blob,URL};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../../docs/week_7/7a/applet.js'),'utf8'),context);
 const el=id=>document.getElementById(id);el('audio').listeners.canplaythrough();return {el,window,events,saved};
}
test('practice markers are not logged and later attempt is flagged for prior listening',async()=>{const h=harness();await h.el('practice').onclick();h.el('audio').currentTime=2;h.el('mark').onclick();assert.ok(!h.events.some(e=>e.detail?.type==='mark'));h.el('audio').currentTime=15;h.el('audio').listeners.timeupdate();await h.el('start').onclick();h.el('audio').listeners.ended();assert.equal(h.window.BC_APP.snapshot().runs[0].exposed,true);});
test('opening then closing transcript remains prior exposure for the next attempt',async()=>{const h=harness();h.el('transcript-details').open=true;h.el('transcript-details').ontoggle();h.el('transcript-details').open=false;h.el('transcript-details').ontoggle();await h.el('start').onclick();h.el('audio').listeners.ended();assert.equal(h.window.BC_APP.snapshot().runs[0].exposed,true);});
test('secondary read-only tab disables recording and cannot overwrite saved work',async()=>{const h=harness();h.window.BC_CLASSROOM.readOnly=true;h.window.BC_APP.controls();assert.equal(h.el('start').disabled,true);await h.el('start').onclick();assert.equal(h.window.BC_APP.snapshot().active,false);h.el('reflection').value='other tab';h.el('reflection').oninput();assert.equal(h.saved.size,0);});
