const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
async function harness({session='',search='',hash='',expired=false}={}){
 const els=new Map(),listeners={},intervals=[],requests=[],ss=new Map(session?[['7a-teacher-session',session]]:[]),ls=new Map();let clears=0;
 class El{constructor(){this.hidden=false;this.textContent='';this.value='';this.children=[];}append(...xs){this.children.push(...xs);}after(){}replaceChildren(...xs){this.children=xs;}focus(){}}
 const el=id=>{if(!els.has(id))els.set(id,new El());return els.get(id);};const clip={id:'clip-a',title:'A'},room={code:'ABCDEFGH',clipId:clip.id,joined:2,submitted:1,open:true,released:false,expiresAt:Date.now()+999999,runs:[],createdAt:Date.now()};
 const app={controls(){},select(){},clearView(){clears++;el('comparison').hidden=true;},compare(){},snapshot:()=>({clip,runs:[],active:false}),last:()=>null,status(){}};
 const win={BC_APP:app,BC_CLIPS:[clip,{id:'clip-b',title:'B'}],addEventListener:(n,f)=>listeners[n]=f};
 const loc={protocol:'https:',origin:'https://example.org',pathname:'/7a.html',search,hash,href:'',reload(){},replace(v){this.href=v;}};
 const ctx={window:win,document:{hidden:false,body:{classList:{add(){},remove(){},toggle(){}}},getElementById:el,createElement:()=>new El(),querySelector:()=>new El()},location:loc,history:{replaceState(){}},localStorage:{getItem:k=>ls.get(k),setItem:(k,v)=>ls.set(k,v)},sessionStorage:{getItem:k=>ss.get(k),setItem:(k,v)=>ss.set(k,v),removeItem:k=>ss.delete(k)},navigator:{locks:{request:async(n,o,f)=>f({})}},performance:{getEntriesByType:()=>[]},crypto:require('node:crypto').webcrypto,URLSearchParams,AbortController,setTimeout,clearTimeout,setInterval:f=>intervals.push(f),clearInterval(){},confirm:()=>true,
 fetch:async(url,opts)=>{const p=new URL(url).pathname;requests.push(p);let status=200,data={};if(p==='/api/teacher/rooms'||p==='/api/teacher/session'){if(expired){status=401;data={error:'Expired'};}else data={username:'teacher',rooms:[room]};}else if(p==='/api/current')data=room;else if(p.endsWith('/join'))data={...room,participant:1,receipts:[],completedAttemptIds:[]};else if(p.endsWith('/audit'))data={attempts:[],activity:[]};else if(p.endsWith('/events'))data={ok:true};else data=room;return {ok:status===200,status,json:async()=>data};}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../../docs/week_7/7a/classroom.js'),'utf8'),ctx);for(let i=0;i<25;i++)await new Promise(r=>setImmediate(r));return {el,win,ss,loc,requests,listeners,intervals,clears:()=>clears,expire:()=>expired=true};
}
test('verified teacher stays teacher even using an old student room link',async()=>{const h=await harness({session:'valid',search:'?room=ABCDEFGH'});assert.equal(h.win.BC_CLASSROOM.mode,'teacher');assert.ok(!h.requests.some(p=>p.endsWith('/join')));assert.equal(h.el('class-teacher').hidden,false);});
test('teacher hash alone grants no teacher role on another computer',async()=>{const h=await harness({hash:'#teacher-room=ABCDEFGH'});assert.equal(h.win.BC_CLASSROOM.mode,'student');assert.ok(h.requests.some(p=>p.endsWith('/join')));assert.equal(h.el('class-teacher').hidden,true);});
test('expired login on load falls back to student without exposing teacher controls',async()=>{const h=await harness({session:'expired',hash:'#teacher-room=ABCDEFGH',expired:true});assert.equal(h.win.BC_CLASSROOM.mode,'student');assert.equal(h.ss.has('7a-teacher-session'),false);assert.equal(h.el('class-teacher').hidden,true);});
test('teacher session expiry during use clears rendered private data',async()=>{const h=await harness({session:'valid'});h.expire();await h.intervals.at(-1)();assert.ok(h.clears()>0);assert.equal(h.el('class-teacher').hidden,true);assert.equal(h.el('teacher-dashboard').hidden,true);assert.equal(h.el('comparison').hidden,true);assert.equal(h.ss.has('7a-teacher-session'),false);});
test('logout in another tab clears this tab teacher view',async()=>{const h=await harness({session:'valid'});h.listeners.storage({key:'7a-teacher-signout'});assert.equal(h.el('class-teacher').hidden,true);assert.equal(h.ss.has('7a-teacher-session'),false);assert.equal(h.el('comparison').hidden,true);});
test('sign-in failure remains visible after student initialization',async()=>{const h=await harness({hash:'#teacher-error=unauthorized'});assert.equal(h.win.BC_CLASSROOM.mode,'student');assert.match(h.el('class-error').textContent,/not authorized/);});
